# Generated by Django 3.1.7 on 2021-09-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20210927_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery_tb',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='gallery_tb',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='gallery_tb',
            name='gallery_type',
        ),
        migrations.RemoveField(
            model_name='gallery_tb',
            name='latest_product',
        ),
    ]
