# Generated by Django 3.1.7 on 2021-10-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20210927_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery_tb',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
